# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FizzBuzz
tagline:          'A version of the classic fizzbuzz kata'
description:      'A practice Laravel 5 package with tests and Continuous Integration'
url:              http://kumuwai.github.io/fizzbuzz
baseurl:          /fizzbuzz/
badges:           '<a href="https://travis-ci.org/kumuwai/fizzbuzz"><img src="https://img.shields.io/travis/kumuwai/fizzbuzz/master.svg"></a> <a href="https://coveralls.io/r/kumuwai/fizzbuzz"><img src="https://coveralls.io/repos/kumuwai/fizzbuzz/badge.svg"></a> <a href="https://scrutinizer-ci.com/g/kumuwai/fizzbuzz"><img src="https://img.shields.io/scrutinizer/g/kumuwai/fizzbuzz.svg"></a> <a href="LICENSE"><img src="https://img.shields.io/badge/license-MIT-blue.svg"></a>'

author:
  name:           'Joel Hatch'
  url:            https://github.com/kumuwai

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/kumuwai
