# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FizzBuzz
tagline:          'A version of the classic fizzbuzz kata'
description:      'A practice Laravel 5 package with tests and Continuous Integration'
url:              http://kumuwai.github.io/fizzbuzz
baseurl:          /fizzbuzz/
badges:           '[![Build Status](https://img.shields.io/travis/kumuwai/fizzbuzz/master.svg)](https://travis-ci.org/kumuwai/fizzbuzz) [![Coverage Status](https://coveralls.io/repos/kumuwai/fizzbuzz/badge.svg)](https://coveralls.io/r/kumuwai/fizzbuzz) [![Quality Score](https://img.shields.io/scrutinizer/g/kumuwai/fizzbuzz.svg)](https://scrutinizer-ci.com/g/kumuwai/fizzbuzz) [![License](https://img.shields.io/badge/license-MIT-blue.svg)](LICENSE.md)'

author:
  name:           'Joel Hatch'
  url:            https://github.com/kumuwai

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/kumuwai
