# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FizzBuzz
tagline:          'A version of the classic fizzbuzz kata'
description:      'A practice Laravel 5 package with tests and Continuous Integration'
url:              http://kumuwai.github.io/fizzbuzz
baseurl:          /fizzbuzz/

author:
  name:           'Joel Hatch'
  url:            https://github.com/kumuwai

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/kumuwai
