# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FizzBuzz
tagline:          'A version of the classic fizzbuzz kata'
description:      'A very simple practice Laravel 5 package to learn techniques of creating and testing a package that will work with Laravel 5. It also includes connections to continuous-integration tools, and can work as a prototype for new packages.'
url:              http://kumuwai.github.io/fizzbuzz
baseurl:          /fizzbuzz/

author:
  name:           'Joel Hatch'
  url:            https://github.com/kumuwai

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/kumuwai
